AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
    Description: 'Environment/region name, prefix for resources'
  ApplicationName:
    Type: String
  S3BucketName:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireNonCurrentVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 3
          - Id: ExpireIncompleteUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
      Tags:
        - Key: Environment
          Value: !Sub ${EnvironmentName}-${ApplicationName}
