AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Dev us-west-2 Postgres
Parameters:
  DevDBAdminUser:
    Default: pwcdevadmin
    NoEcho: 'true'
    Description: admin user
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters
Resources:
  DevDbAdminSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      KmsKeyId: alias/aws/secretsmanager
      GenerateSecretString:
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        PasswordLength: 32
        ExcludeCharacters: /"@\\
  DevDbAppUserSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      KmsKeyId: alias/aws/secretsmanager
      GenerateSecretString:
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        PasswordLength: 32
        ExcludeCharacters: /"@\\
  DevPgSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for dev private vpc subnet azs us-west-2a|b
      SubnetIds:
        - subnet-044c7a168f611f884 # Private subnet 1 (us-west-2a)
        - subnet-0eadc79f52796d341 # Private subnet 2 (us-west-2b)
  DevPgDbInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: db.t3.medium
      AllocatedStorage: '75'
      DBName: pwc
      Engine: postgres
      EngineVersion: '17.5'
      MasterUsername: !Ref DevDBAdminUser
      MasterUserPassword: 
        'Fn::Sub': '{{resolve:secretsmanager:${DevDbAdminSecret}}}'
      Port: '5432'
      DBInstanceIdentifier: dev-uw2
      VPCSecurityGroups: 
        - sg-0fb997782712f6f4f
      DBSubnetGroupName: !Ref DevPgSubnetGroup
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: standard
      BackupRetentionPeriod: 1
      DeleteAutomatedBackups: true
      DeletionProtection: false
      MultiAZ: true
