AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create CloudWatch alarms for DynamoDB read capacity monitoring'

Parameters:
  AlarmNotificationEmail:
    Type: String
    Description: Email address to receive alarm notifications
    Default: devops@proscore.ai
  
  ReadCapacityThreshold:
    Type: Number
    Description: Threshold for consumed read capacity units (percentage of provisioned capacity)
    Default: 80
    MinValue: 1
    MaxValue: 100

Resources:
  ReadCapacityAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: DynamoDB Read Capacity Alarm Topic
      TopicName: DynamoDBReadCapacityAlarmTopic

  ReadCapacityAlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ReadCapacityAlarmTopic
      Protocol: email
      Endpoint: !Ref AlarmNotificationEmail

  StepFunctionImportErrorLogsReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ReadCapacityAlarm-step-function-import-error-logs
      AlarmDescription: Alarm when read capacity exceeds threshold for step-function-import-error-logs
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref ReadCapacityThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: step-function-import-error-logs
      AlarmActions:
        - !Ref ReadCapacityAlarmTopic
      InsufficientDataActions:
        - !Ref ReadCapacityAlarmTopic
      OKActions:
        - !Ref ReadCapacityAlarmTopic

  StepFunctionImportErrorLogsProdReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ReadCapacityAlarm-step-function-import-error-logs-prod
      AlarmDescription: Alarm when read capacity exceeds threshold for step-function-import-error-logs-prod
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref ReadCapacityThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: step-function-import-error-logs-prod
      AlarmActions:
        - !Ref ReadCapacityAlarmTopic
      InsufficientDataActions:
        - !Ref ReadCapacityAlarmTopic
      OKActions:
        - !Ref ReadCapacityAlarmTopic

  StepFunctionImportErrorLogsTestReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ReadCapacityAlarm-step-function-import-error-logs-test
      AlarmDescription: Alarm when read capacity exceeds threshold for step-function-import-error-logs-test
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref ReadCapacityThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: step-function-import-error-logs-test
      AlarmActions:
        - !Ref ReadCapacityAlarmTopic
      InsufficientDataActions:
        - !Ref ReadCapacityAlarmTopic
      OKActions:
        - !Ref ReadCapacityAlarmTopic

  ApiGatewayAiImportClientAliasesReadCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ReadCapacityAlarm-api-gateway-ai-import-client-aliases
      AlarmDescription: Alarm when read capacity exceeds threshold for api-gateway-ai-import-client-aliases
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref ReadCapacityThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: TableName
          Value: api-gateway-ai-import-client-aliases
      AlarmActions:
        - !Ref ReadCapacityAlarmTopic
      InsufficientDataActions:
        - !Ref ReadCapacityAlarmTopic
      OKActions:
        - !Ref ReadCapacityAlarmTopic
