---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-west-2:638891785980:generatedTemplate/08d6b6ca-1f34-4ae6-870c-da6d017ef328"
Resources:
  IAMManagedPolicyPolicydevlambda:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    Properties:
      ManagedPolicyName: "DevLambda"
      Path: "/"
      Description: "Policy is for accessing Lambda function for development team"
      Groups:
      - "ImportLambdaDevelopers"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              iam:PassedToService: "lambda.amazonaws.com"
          Resource: "arn:aws:iam::638891785980:role/lambda-execution-role"
          Action: "iam:PassRole"
          Effect: "Allow"
          Sid: "VisualEditor0"
        - Resource: "*"
          Action:
          - "lambda:CreateFunction"
          - "cloudwatch:PutMetricData"
          - "cloudwatch:GetMetricData"
          - "lambda:GetFunctionConfiguration"
          - "cloudwatch:ListMetrics"
          - "cloudwatch:DescribeAlarmHistory"
          - "lambda:ListTags"
          - "cloudwatch:ListDashboards"
          - "lambda:ListLayers"
          - "lambda:ListCodeSigningConfigs"
          - "lambda:GetAlias"
          - "cloudwatch:DescribeInsightRules"
          - "lambda:InvokeFunctionUrl"
          - "cloudwatch:GetDashboard"
          - "lambda:ListFunctions"
          - "lambda:InvokeFunction"
          - "lambda:GetFunction"
          - "lambda:ListAliases"
          - "lambda:UpdateFunctionConfiguration"
          - "lambda:ListFunctionUrlConfigs"
          - "lambda:GetFunctionUrlConfig"
          - "cloudwatch:GetMetricStatistics"
          - "lambda:UpdateFunctionCode"
          - "lambda:AddPermission"
          - "lambda:ListFunctionsByCodeSigningConfig"
          - "s3:ListAllMyBuckets"
          - "cloudwatch:DescribeAlarms"
          - "lambda:PublishVersion"
          - "lambda:GetPolicy"
          Effect: "Allow"
          Sid: "VisualEditor1"
        - Resource:
          - "arn:aws:s3:::gemini-processed-payroll-summaries/*"
          - "arn:aws:s3:::gemini-processed-timesheets/*"
          - "arn:aws:s3:::raw-employee-imports/*"
          - "arn:aws:s3:::raw-payroll-summary-imports/*"
          - "arn:aws:s3:::raw-project-employee-imports/*"
          - "arn:aws:s3:::raw-rei-imports/*"
          - "arn:aws:s3:::raw-timesheet-imports/*"
          - "arn:aws:s3:::ai-gemini-processed/*"
          - "arn:aws:s3:::ai-timesheet-input/*"
          - "arn:aws:s3:::payroll-import-dev/*"
          - "arn:aws:logs:*:*:*"
          Action:
          - "s3:PutObject"
          - "s3:GetObject"
          - "logs:CreateLogStream"
          - "logs:CreateLogGroup"
          - "logs:PutLogEvents"
          Effect: "Allow"
          Sid: "VisualEditor2"
        - Resource:
          - "arn:aws:s3:::gemini-processed-payroll-summaries"
          - "arn:aws:s3:::gemini-processed-timesheets"
          - "arn:aws:s3:::raw-employee-imports"
          - "arn:aws:s3:::raw-payroll-summary-imports"
          - "arn:aws:s3:::raw-project-employee-imports"
          - "arn:aws:s3:::raw-rei-imports"
          - "arn:aws:s3:::raw-timesheet-imports"
          - "arn:aws:s3:::ai-gemini-processed"
          - "arn:aws:s3:::ai-timesheet-input"
          - "arn:aws:s3:::payroll-import-dev"
          - "arn:aws:logs:*:*:*"
          Action:
          - "s3:PutBucketNotification"
          - "logs:DescribeLogStreams"
          - "logs:GetLogEvents"
          - "s3:ListBucket"
          - "logs:FilterLogEvents"
          - "s3:GetBucketLocation"
          Effect: "Allow"
          Sid: "VisualEditor3"
        - Resource: "arn:aws:logs:*:*:*"
          Action: "logs:DescribeLogGroups"
          Effect: "Allow"
          Sid: "VisualEditor4"
      Roles:
      - "lambda-execution-role"
      Users: []

